## ID 10319 - Monthly Percentage Difference.sql ##

WITH CTE_TOTAL_REVENUE AS (
SELECT TO_CHAR(CREATED_AT,'YYYY-MM') AS YEAR_MONTH,
       SUM(VALUE) AS TOTAL_REVENUE
FROM SF_TRANSACTIONS
GROUP BY TO_CHAR(CREATED_AT,'YYYY-MM')
ORDER BY 1 ASC
),
CTE_THIS_VS_LAST_MONTH_REVENUE AS (
SELECT YEAR_MONTH,
       TOTAL_REVENUE AS THIS_MONTH_REVENUE,
       LAG(TOTAL_REVENUE,1,0)OVER(ORDER BY YEAR_MONTH) AS LAST_MONTH_REVENUE
FROM CTE_TOTAL_REVENUE
)
SELECT YEAR_MONTH,
       ROUND(((THIS_MONTH_REVENUE - LAST_MONTH_REVENUE)/NULLIF(LAST_MONTH_REVENUE,0))*100,2) AS REVENUE_DIFF_PCT
FROM CTE_THIS_VS_LAST_MONTH_REVENUE;
