# ID 10548 - Top Actor Ratings by Genre #

WITH CTE_AVG_RATING AS (
SELECT ACTOR_NAME,
       GENRE, 
       COUNT(*) AS MOVIE_COUNT,
       AVG(MOVIE_RATING) AS AVG_RATING
FROM TOP_ACTORS_RATING
GROUP BY ACTOR_NAME,
       GENRE
ORDER BY ACTOR_NAME
),
CTE_RATING_RANK AS (
SELECT ACTOR_NAME,
       GENRE,
       MOVIE_COUNT,
       AVG_RATING,
       DENSE_RANK()OVER(PARTITION BY ACTOR_NAME ORDER BY MOVIE_COUNT DESC,AVG_RATING DESC) AS DRANK

FROM CTE_AVG_RATING
),
CTE_RANK_BY_AVG_RATING AS(
SELECT ACTOR_NAME,
       GENRE,
       AVG_RATING,
       DENSE_RANK()OVER(ORDER BY AVG_RATING DESC) AS RANK

FROM CTE_RATING_RANK
WHERE DRANK = 1
)

SELECT ACTOR_NAME,
      GENRE,
      AVG_RATING,
      RANK
FROM CTE_RANK_BY_AVG_RATING
WHERE RANK <=3;
