WITH CTE_EMPLOYEES AS (
SELECT EMPLOYEE_NAME, 
       SALARY, 
       DENSE_RANK()OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS DENSE_RANK
FROM EMPLOYEES
)

SELECT EMPLOYEE_NAME,
       SALARY
FROM CTE_EMPLOYEES
WHERE RNK = 3;