## ID 2146 - Department Manager and Employee Salary Comparison ##

WITH CTE_DEPT_AVG_SALARY AS (
SELECT DEPARTMENT,
       ROUND(AVG(SALARY)) AS DEPARTMENT_AVG_SALARY
FROM EMPLOYEE_O
WHERE EMPLOYEE_TITLE <> 'Manager'
GROUP BY DEPARTMENT
)

SELECT A.DEPARTMENT,
       A.ID AS EMPLOYEE_ID,
       A.SALARY AS EMPLOYEE_SALARY,
       B.SALARY AS MANAGERS_SALARY,
       C.DEPARTMENT_AVG_SALARY
FROM EMPLOYEE_O AS A

LEFT JOIN EMPLOYEE_O AS B
ON A.DEPARTMENT = B.DEPARTMENT
AND B.EMPLOYEE_TITLE = 'Manager'

LEFT JOIN CTE_DEPT_AVG_SALARY AS C
ON A.DEPARTMENT = C.DEPARTMENT
ORDER BY A.DEPARTMENT ASC,
         A.SALARY DESC;
